#!/bin/bash

set -Eeu -o pipefail

TAG="helloservice"

_build(){
    ./gradlew assemble
    docker build . -t ${TAG}
}

_cleanup() {
  docker-compose kill
  docker-compose rm -fv
}

compose() {
  trap _cleanup EXIT TERM
  docker-compose up
}

_run() {
  docker run -t ${TAG}
}

usage() {
    echo "Usage: $0 build | run"
    exit 0
}

cd $(dirname $0)

CMD=${1:-}
shift || true
case ${CMD} in
  build) _build ;;
  run) _run ;;
  *) usage ;;
esac