version: "3"
services:
  helloservice:
    image: helloservice
    container_name: "helloservice"
  coroutines:
    image: coroutines
    container_name: "coroutines"
    ports:
      - 8080:8080
    depends_on:
      - helloservice