version: "2"
services:
  helloservice:
    image: helloservice
    container_name: "helloservice"
  worldservice:
    image: worldservice
    container_name: "worldservice"
  coroutines:
    image: coroutines
    container_name: "coroutines"
    ports:
      - 8080:8080
    depends_on:
      - helloservice
      - worldservice